import type { Algorithm } from '../types/algorithm.types';

export const ALGORITHM_CATALOG: Algorithm[] = [
  {
    id: 'bubble-sort',
    name: 'Bubble Sort (Sắp xếp nổi bọt)',
    category: 'Sorting',
    difficulty: 'Easy',
    timeComplexity: 'O(N²)',
    spaceComplexity: 'O(1)',
  },
  {
    id: 'selection-sort',
    name: 'Selection Sort (Sắp xếp chọn)',
    category: 'Sorting',
    difficulty: 'Easy',
    timeComplexity: 'O(N²)',
    spaceComplexity: 'O(1)',
  },
  {
    id: 'insertion-sort',
    name: 'Insertion Sort (Sắp xếp chèn)',
    category: 'Sorting',
    difficulty: 'Easy',
    timeComplexity: 'O(N²)',
    spaceComplexity: 'O(1)',
  },
  {
    id: 'quick-sort',
    name: 'Quick Sort (Sắp xếp nhanh)',
    category: 'Sorting',
    difficulty: 'Medium',
    timeComplexity: 'O(N log N)',
    spaceComplexity: 'O(log N)',
  },
  {
    id: 'merge-sort',
    name: 'Merge Sort (Sắp xếp trộn)',
    category: 'Sorting',
    difficulty: 'Medium',
    timeComplexity: 'O(N log N)',
    spaceComplexity: 'O(N)',
  },
  {
    id: 'linear-search',
    name: 'Linear Search (Tìm kiếm tuần tự)',
    category: 'Searching',
    difficulty: 'Easy',
    timeComplexity: 'O(N)',
    spaceComplexity: 'O(1)',
  },
  {
    id: 'binary-search',
    name: 'Binary Search (Tìm kiếm nhị phân)',
    category: 'Searching',
    difficulty: 'Medium',
    timeComplexity: 'O(log N)',
    spaceComplexity: 'O(1)',
  },
  {
    id: 'stack',
    name: 'Stack (Ngăn xếp - LIFO)',
    category: 'Stack-Queue',
    difficulty: 'Easy',
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(N)',
  },
  {
    id: 'queue',
    name: 'Queue (Hàng đợi - FIFO)',
    category: 'Stack-Queue',
    difficulty: 'Easy',
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(N)',
  },
  {
    id: 'bst',
    name: 'Binary Search Tree (Cây BST)',
    category: 'Tree',
    difficulty: 'Medium',
    timeComplexity: 'O(log N)',
    spaceComplexity: 'O(N)',
  },
];
