import type { Algorithm } from '../types/algorithm.types';

export const ALGORITHM_CATALOG: Algorithm[] = [
  {
    id: 'linear-search',
    name: 'Linear Search (Tìm kiếm tuần tự)',
    category: 'Searching',
    difficulty: 'Easy',
    timeComplexity: 'O(N)',
    spaceComplexity: 'O(1)',
  },
  {
    id: 'binary-search',
    name: 'Binary Search (Tìm kiếm nhị phân)',
    category: 'Searching',
    difficulty: 'Medium',
    timeComplexity: 'O(log N)',
    spaceComplexity: 'O(1)',
  },
  {
    id: 'sliding-window',
    name: 'Sliding Window (Cửa sổ trượt)',
    category: 'Searching',
    difficulty: 'Medium',
    timeComplexity: 'O(N)',
    spaceComplexity: 'O(1)',
  },
  {
    id: 'stack',
    name: 'Stack (Ngăn xếp - LIFO)',
    category: 'Stack-Queue',
    difficulty: 'Easy',
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(N)',
  },
  {
    id: 'queue',
    name: 'Queue (Hàng đợi - FIFO)',
    category: 'Stack-Queue',
    difficulty: 'Easy',
    timeComplexity: 'O(1)',
    spaceComplexity: 'O(N)',
  },
  {
    id: 'monotonic-stack',
    name: 'Monotonic Stack (Ngăn xếp đơn điệu)',
    category: 'Stack-Queue',
    difficulty: 'Medium',
    timeComplexity: 'O(N)',
    spaceComplexity: 'O(N)',
  },
  {
    id: 'bst',
    name: 'Binary Search Tree (Cây BST)',
    category: 'Tree',
    difficulty: 'Medium',
    timeComplexity: 'O(log N)',
    spaceComplexity: 'O(N)',
  },
  {
    id: 'bfs',
    name: 'Breadth-First Search (Duyệt BFS)',
    category: 'Tree',
    difficulty: 'Medium',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
  },
  {
    id: 'dfs',
    name: 'Depth-First Search (Duyệt DFS)',
    category: 'Tree',
    difficulty: 'Medium',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
  },
  {
    id: 'dijkstra',
    name: 'Dijkstra Shortest Path (Đường đi ngắn nhất)',
    category: 'Tree',
    difficulty: 'Hard',
    timeComplexity: 'O((V + E) log V)',
    spaceComplexity: 'O(V)',
  },
];
